services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    env_file: db.env
    networks:
      - nc_net

  app:
    image: nextcloud
    restart: unless-stopped
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    env_file: 
    - app.env
    - db.env
    networks:
      - nc_net
      - reverse-proxy_net

  signal:
    image: ghcr.io/nextcloud-releases/aio-talk:latest
    init: true
    restart: unless-stopped
    env_file: signal.env
    networks:
      - reverse-proxy_net
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"

volumes:
  nextcloud:
  db:

networks:
  nc_net:
    external: false
  reverse-proxy_net:
    external: true
